update nixpkgs (#4733)
Update nixpkgs to latest `unstable`.

Remove Servant pin as we get Servant 0.20.3 from nixpkgs now. And use the
upstreamed `MultiVerb`.

Update forked version of Amazonka.

Cleanup text-builder deps: There's now a newer minor version of text-builder
core provided by nixpkgs. The provided text-builder-core version is exactly
those we used bofore.

Cleanup jailbreaks

Allow fallback when querying cachix as some dependencies don't work. E.g.

```
error: unable to download
'https://wire-server.cachix.org/nar/efd7da48cfc88cd2bc30eae66a648c497f27b7132d248d8964b12cb61f603820.nar.zst':
HTTP error 500

       response body:

       Tried serving NAR from storage and hit maximum retries limit.

error: some substitutes for the outputs of derivation
'/nix/store/vb93g275dqnsjfbx0z1l9daxrc3ngwdb-ff-0.13.0.tar.gz.drv'
failed (usually happens due to networking issues); try '--fallback' to
build derivation from source
```