remove debian package information
Exception: brig, which needs to keep its deb folder, as it contains the
email templates referred to elsewhere and copied during docker image
builds.