updatePhone deflake (#1874)
* updatePhone deflake debugging information

This is about https://wearezeta.atlassian.net/browse/BE-526

I think what's happening is that one test that tests the phone blocking
adds a record into the brig.excluded_phones entry. Then, another,
unrelated test, if unlucky enough to randomly generate a phone number
contained under that prefix, fails in the PUT /self/phone call.

* 1) update integration test output to give better information and link
  to a flaky test description
* 2) change the code to (hopefully) avoid this flake to re-occur.

The changes to integration tests will lead to the following output on
failure:

  user
    account
      put /i/users/:uid/sso-id:
        Exception: Assertions failed:
         1: 202 =/= 403
         2: updatePhone (PUT /self/phone): failed to update to Phone {fromPhone = "+046965171332989"} - might be a flaky test tracked in https://wearezeta.atlassian.net/browse/BE-526

        Response was:

        Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("Transfer-Encoding","chunked"),("Date","Wed, 20 Oct 2021 14:41:27 GMT"),("Server","Warp/3.3.13"),("Content-Encoding","gzip"),("Content-Type","application/json")], responseBody = Just "{\"code\":403,\"message\":\"The given phone number has been blacklisted due to suspected abuse or a complaint.\",\"label\":\"blacklisted-phone\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
        CallStack (from HasCallStack):
          error, called at src/Bilge/Assert.hs:89:5 in bilge-0.22.0-5tCtgpJGKRb38JsbN4shGd:Bilge.Assert
          <!!, called at src/Bilge/Assert.hs:107:19 in bilge-0.22.0-5tCtgpJGKRb38JsbN4shGd:Bilge.Assert
          !!!, called at test/integration/Util.hs:735:3 in main:Util
          updatePhone, called at test/integration/API/User/Account.hs:1230:11 in main:API.User.Account

* undo changes in src as they make another test fail

* Add a cleanup line

* fixup

* Hi CI