Delete makedeb and bonanza (#2600)
* Delete bonanza

The tool is no longer required. Please use 'StructuredJSON' log format.

* Delete makedeb and all references to it

* Add changelog

* remove debian package information

Exception: brig, which needs to keep its deb folder, as it contains the
email templates referred to elsewhere and copied during docker image
builds.

* Makefiles: delete references to DEBian packages

Co-authored-by: jschaul <jschaul@users.noreply.github.com>